### ISSUE TITLE
Actual Collision?

### ISSUE THREAD

**Issue by Thundros** [vanruesc/octree-helper#1]
Hi, EXCELLENT work! Keep up the GREAT work! <3 I'd just like to ask if you could create a demo using octrees for high-speed terrain collision / sliding?

Thank you!

**Comment by vanruesc** [comment]
Hi, thanks for the kind words! 

I have mainly used the sparse-octree for spatial organization of voxel data and haven't looked into physics integration yet. I plan on moving a lot of the octree code from the [rabbit-hole](https://github.com/vanruesc/rabbit-hole) module to the sparse-octree module first. In terms of priority, the completion of the rabbit-hole project comes before the physics integration.

Development is stagnant on this front, though, because work is currently taking priority.

**Comment by Thundros** [comment]
Hi @vanruesc : Are you able to add actual collision with the new systyem? I am VERY much interested in beta testing.

Thank You! ^_^

**Comment by vanruesc** [comment]
@Thundros Yes, well... kindof. An octree can be used for broadphase collision detection:

You essentially ask the octree which objects could potentially collide and get a list back. This process is fast and the query can be limited to a specific area in 3D space. The hard part about the implementation is the management of moving objects and objects that straddle multiple octants.
